# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1916e059660d38f60928ca0caa029aa086f62a5a6e9ff151dc9c60d575c759c6ef93b4c96db17fc4816e4031c5c295eb851f5d27601d1a0bf9e8055c4c24707e

test:
  secret_key_base: 3278743fd095b0f3129cb6a248463ffd1171d7270820e7bbe8f8c2f28184f33bc7bd231e8108495679219a08a50f7ce36dcff999458e1e7d3813ea7d24bbb411

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
